// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBx7Q2DbxxZYySU--XDgcackpnHMj0aV0',
    appId: '1:783541556247:web:e5ddbe9bdc3d73a9983852',
    messagingSenderId: '783541556247',
    projectId: 'taskmanager-97585',
    authDomain: 'taskmanager-97585.firebaseapp.com',
    storageBucket: 'taskmanager-97585.firebasestorage.app',
    measurementId: 'G-89F6F4BEF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1wtwKsrMVFF5xzFjwDHpTkOa_SOrH-Zg',
    appId: '1:783541556247:android:2f3c32557fc3ff9d983852',
    messagingSenderId: '783541556247',
    projectId: 'taskmanager-97585',
    storageBucket: 'taskmanager-97585.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnrFmcLHR0ivhK2svQAo9HMlSp6aM2ATE',
    appId: '1:783541556247:ios:b1dcda93c2096cac983852',
    messagingSenderId: '783541556247',
    projectId: 'taskmanager-97585',
    storageBucket: 'taskmanager-97585.firebasestorage.app',
    iosBundleId: 'com.example.taskmanagerMobile',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnrFmcLHR0ivhK2svQAo9HMlSp6aM2ATE',
    appId: '1:783541556247:ios:b1dcda93c2096cac983852',
    messagingSenderId: '783541556247',
    projectId: 'taskmanager-97585',
    storageBucket: 'taskmanager-97585.firebasestorage.app',
    iosBundleId: 'com.example.taskmanagerMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBx7Q2DbxxZYySU--XDgcackpnHMj0aV0',
    appId: '1:783541556247:web:88da059a2297c323983852',
    messagingSenderId: '783541556247',
    projectId: 'taskmanager-97585',
    authDomain: 'taskmanager-97585.firebaseapp.com',
    storageBucket: 'taskmanager-97585.firebasestorage.app',
    measurementId: 'G-F6D65EDY74',
  );
}
